version: '3.8'

services:
  web:
    build: ./backend
    volumes:
      - ./backend:/usr/src/backend
    container_name : nestjs
    ports: 
      - 3000:3000

  frontend:
    build: ./frontend
    stdin_open: true
    volumes:
    - ./frontend:/usr/src/frontend
    container_name : angular-app
    ports: 
      - 4200:4200



